version: "3"
services:
  manager-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    restart: always
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - manager-php-fpm
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
  manager-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
      - ./docker/ssl:/etc/nginx/ssl
      - ./composer:/root/.composer/cache
      - ./docker/php/default.ini:/usr/local/etc/php/php.ini
  manager-pgsql:
    build:
      context: ./docker
      dockerfile: pgsql.docker
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=puckit
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"